# Docker compose file to simulate a sentry node setup.
#
#
# Setup:
#
# Validator A is not supposed to be connected to the public internet. Instead it
# connects to a sentry node (sentry-a) which connects to the public internet.
# Validator B can reach validator A via sentry node A and vice versa.
#
#
# Usage:
#
# 1. Build `target/release/substrate` binary: `cargo build --release`
#
# 2. Start networks and containers: `sudo docker-compose -f .maintain/sentry-node/docker-compose.yml up`
#
# 3. Reach:
#   - polkadot/apps on localhost:3000
#   - validator-a: localhost:9944
#   - validator-b: localhost:9945
#   - sentry-a: localhost:9946

version: "3.7"
services:

  validator-a:
    ports:
      - "9944:9944"
    # volumes:
    #   - ./target/release/centrifuge-chain:/usr/local/bin/centrifuge-chain
    image: centrifugeio/centrifuge-chain:sentry-bug
    networks:
      - network-a
    command:
      - centrifuge-chain
      # Local node id: QmRpheLN4JWdAnY7HGJfWFNbfkQCb6tFf4vvA6hgjMZKrR
      - "--node-key"
      - "0000000000000000000000000000000000000000000000000000000000000001"
      - "--chain=local"
      - "--validator"
      - "--alice"
      - "--listen-addr=/dns4/sentry-a/tcp/30333"
      - "--reserved-only"
      - "--sentry-nodes"
      - "/dns4/sentry-a/tcp/30333/p2p/QmV7EhW6J6KgmNdr558RH1mPx2xGGznW7At4BhXzntRFsi"
      - "--reserved-nodes"
      - "/dns4/sentry-a/tcp/30333/p2p/QmV7EhW6J6KgmNdr558RH1mPx2xGGznW7At4BhXzntRFsi"
      # Not only bind to localhost.
      # - "--unsafe-ws-external"
      # - "--unsafe-rpc-external"
      # - "--log"
      # - "sub-libp2p=trace"
      # - "--log"
      # - "afg=trace"
      - "--log"
      - "sub-authority-discovery=trace"
      - "--no-telemetry"
      # - "--rpc-cors=all"

  sentry-a:
    image: centrifugeio/centrifuge-chain:sentry-bug
    ports:
      - "9946:9944"
    # volumes:
    #   - ./target/release/centrifuge-chain:/usr/local/bin/centrifuge-chain
    networks:
      - network-a
      - internet
    command:
      - centrifuge-chain
      # Local node id: QmV7EhW6J6KgmNdr558RH1mPx2xGGznW7At4BhXzntRFsi
      - "--node-key"
      - "0000000000000000000000000000000000000000000000000000000000000003"
      - "--chain=local"
      - "--name=alice-sentry"
      # - "--bootnodes"
      # - "/dns4/validator-a/tcp/30333/p2p/QmRpheLN4JWdAnY7HGJfWFNbfkQCb6tFf4vvA6hgjMZKrR"
      - "--bootnodes"
      - "/dns4/validator-b/tcp/30333/p2p/QmSVnNf9HwVMT1Y4cK1P6aoJcEZjmoTXpjKBmAABLMnZEk"
      - "--reserved-nodes"
      - "/dns4/validator-a/tcp/30333/p2p/QmRpheLN4JWdAnY7HGJfWFNbfkQCb6tFf4vvA6hgjMZKrR"
      - "--no-telemetry"
      # - "--rpc-cors=all"
      # Not only bind to localhost.
      # - "--unsafe-ws-external"
      # - "--unsafe-rpc-external"
      - "--log"
      - "sub-authority-discovery=trace"
      - "--sentry"

  validator-b:
    ports:
      - "9945:9944"
    # volumes:
    #   - ./target/release/centrifuge-chain:/usr/local/bin/centrifuge-chain
    image: centrifugeio/centrifuge-chain:sentry-bug
    networks:
      - network-b
    command:
      - centrifuge-chain
      # Local node id: QmSVnNf9HwVMT1Y4cK1P6aoJcEZjmoTXpjKBmAABLMnZEk
      - "--node-key"
      - "0000000000000000000000000000000000000000000000000000000000000002"
      - "--chain=local"
      - "--validator"
      - "--bob"
      - "--listen-addr=/dns4/sentry-b/tcp/30333"
      - "--reserved-only"
      - "--sentry-nodes"
      - "/dns4/sentry-b/tcp/30333/p2p/QmZT1VPZwqWx3J7kPUgfMvuQtDJpPsC5pjpH1EcZycXYwH"
      - "--reserved-nodes"
      - "/dns4/sentry-b/tcp/30333/p2p/QmZT1VPZwqWx3J7kPUgfMvuQtDJpPsC5pjpH1EcZycXYwH"
      # Not only bind to localhost.
      # - "--unsafe-ws-external"
      # - "--unsafe-rpc-external"
      # - "--log"
      # - "sub-libp2p=trace"
      # - "--log"
      # - "afg=trace"
      - "--log"
      - "sub-authority-discovery=trace"
      - "--no-telemetry"
      # - "--rpc-cors=all"

  sentry-b:
    image: centrifugeio/centrifuge-chain:sentry-bug
    ports:
      - "9947:9944"
    # volumes:
    #   - ./target/release/centrifuge-chain:/usr/local/bin/centrifuge-chain
    networks:
      - network-b
      - internet
    command:
      - centrifuge-chain
      # Local node id: QmZT1VPZwqWx3J7kPUgfMvuQtDJpPsC5pjpH1EcZycXYwH # TODO replace
      - "--node-key"
      - "0000000000000000000000000000000000000000000000000000000000000004"
      - "--chain=local"
      - "--name=dave-sentry"
      - "--bootnodes"
      - "/dns4/validator-a/tcp/30333/p2p/QmRpheLN4JWdAnY7HGJfWFNbfkQCb6tFf4vvA6hgjMZKrR"
      # - "--bootnodes"
      # - "/dns4/validator-b/tcp/30333/p2p/QmSVnNf9HwVMT1Y4cK1P6aoJcEZjmoTXpjKBmAABLMnZEk"
      - "--reserved-nodes"
      - "/dns4/validator-b/tcp/30333/p2p/QmSVnNf9HwVMT1Y4cK1P6aoJcEZjmoTXpjKBmAABLMnZEk"
      - "--no-telemetry"
      # - "--rpc-cors=all"
      # Not only bind to localhost.
      # - "--unsafe-ws-external"
      # - "--unsafe-rpc-external"
      - "--log"
      - "sub-authority-discovery=trace"
      - "--sentry"

  # ui:
  #   image: polkadot-js/apps
  #   ports:
  #     - "3000:80"

networks:
  network-a:
  network-b:
  internet:
